# Generated by Django 5.2.4 on 2025-07-31 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiscuitVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='biscuit/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('MG', 'Marie Gold'), ('GD', 'Good Day'), ('HS', 'Hide & Seek'), ('BB', 'Bourbon'), ('KJ', 'Krackjack'), ('OO', 'Oreo')], max_length=2)),
            ],
        ),
    ]
